[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[[redirects]]
  from = "/api/view"
  to   = "/.netlify/functions/view"
  status = 200

[[redirects]]
  from = "/api/share"
  to   = "/.netlify/functions/share"
  status = 200

[[redirects]]
  from = "/api/lock"
  to   = "/.netlify/functions/lock"
  status = 200

[[redirects]]
  from = "/api/confirm"
  to   = "/.netlify/functions/confirm"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


[[redirects]]
  from = "/api/delete"
  to   = "/.netlify/functions/delete"
  status = 200
